default: &default
  adapter: mysql2
  username: root
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: feeder_development

test:
  <<: *default
  database: feeder_test

production:
  <<: *default
  username: <%= ENV["MYSQL_USERNAME"] %>
  password: <%= ENV["MYSQL_PASSWROD"] %>
  pool: 25
  database: feeder
